"""Add razorpay tracking fields

Revision ID: 403ea243d1a9
Revises: 7795d836f579
Create Date: 2026-08-24 20:56:12.915216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403ea243d1a9'
down_revision: Union[str, Sequence[str], None] = '7795d836f579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_status')
    op.drop_column('transactions', 'razorpay_payment_id')
    op.drop_column('transactions', 'razorpay_order_id')
    # ### end Alembic commands ###
