"""add_avatar_url_to_user

Revision ID: 523926d781ec
Revises: fc8ed9437239
Create Date: 2026-09-01 17:13:08.443069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523926d781ec'
down_revision: Union[str, Sequence[str], None] = 'fc8ed9437239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_public_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receipt_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_transaction_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_webhook_events_event_key'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_external_auth_provider'), table_name='users')
    op.drop_index(op.f('ix_external_subject'), table_name='users')
    op.create_index(op.f('ix_users_external_auth_provider'), 'users', ['external_auth_provider'], unique=False)
    op.create_index(op.f('ix_users_external_subject'), 'users', ['external_subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_subject'), table_name='users')
    op.drop_index(op.f('ix_users_external_auth_provider'), table_name='users')
    op.create_index(op.f('ix_external_subject'), 'users', ['external_subject'], unique=False)
    op.create_index(op.f('ix_external_auth_provider'), 'users', ['external_auth_provider'], unique=False)
    op.drop_column('users', 'avatar_url')
    op.create_table('webhook_events',
    sa.Column('event_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_key', name=op.f('webhook_events_pkey'))
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_key'), 'webhook_events', ['event_key'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_notifications_idempotency_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_transaction_id'), 'notifications', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_notifications_receipt_id'), 'notifications', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receipt_jsonb', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('receipts_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('receipts_pkey')),
    sa.UniqueConstraint('transaction_id', name=op.f('receipts_transaction_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_receipts_public_id'), 'receipts', ['public_id'], unique=True)
    # ### end Alembic commands ###
