import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';

export const SimpleStory: React.FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start end", "center center"]
  });

  const leftX = useTransform(scrollYProgress, [0, 1], ["-100%", "0%"]);
  const rightX = useTransform(scrollYProgress, [0, 1], ["100%", "0%"]);
  const opacity = useTransform(scrollYProgress, [0.5, 1], [0, 1]);

  return (
    <div ref={containerRef} className="h-[200vh] relative w-full z-[30]">
      <section className="sticky top-0 h-screen w-full flex items-center bg-app-primary px-6 overflow-hidden origin-top shadow-2xl">
        <div className="max-w-7xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-16 md:gap-32">
          
          {/* Left: The AI Action (Slides from Left) */}
          <motion.div 
            style={{ x: leftX, opacity }}
            className="flex items-center justify-center lg:justify-start order-2 lg:order-1"
          >
            <div className="w-full max-w-md p-10 relative overflow-hidden bg-app-card border border-[#F2EFE9]/10 rounded-sm shadow-2xl">
              {/* Ambient Noise / Texture */}
              <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.05] mix-blend-overlay pointer-events-none" />
              
              <div className="relative z-10 text-app-textPrimary">
                <div className="flex justify-between items-start mb-12 border-b border-[#F2EFE9]/10 pb-6">
                  <div className="font-mono text-xs tracking-[0.2em] text-app-textMuted uppercase font-bold">
                    Proposal
                  </div>
                  <div className="font-mono text-[9px] tracking-widest text-app-textPrimary border border-[#F2EFE9]/30 px-2 py-1 uppercase font-bold bg-[#F2EFE9]/5">
                    AI Transaction
                  </div>
                </div>

                <div className="space-y-8">
                  <div className="flex items-end justify-between border-b border-[#F2EFE9]/10 pb-4">
                    <div className="font-mono text-[10px] text-app-textMuted tracking-widest mb-1 font-bold">AMOUNT</div>
                    <div className="font-editorial text-4xl text-app-textPrimary font-extrabold">₹75,000</div>
                  </div>

                  <div className="flex items-end justify-between border-b border-[#F2EFE9]/10 pb-4">
                    <div className="font-mono text-[10px] text-app-textMuted tracking-widest mb-1 font-bold">MERCHANT</div>
                    <div className="font-editorial text-2xl text-app-textPrimary font-bold tracking-tight uppercase">TechStore Inc.</div>
                  </div>

                  <div className="flex items-end justify-between border-b border-[#F2EFE9]/10 pb-4">
                    <div className="font-mono text-[10px] text-app-textMuted tracking-widest mb-1 font-bold">ITEM</div>
                    <div className="font-editorial text-2xl text-app-textPrimary font-bold tracking-tight uppercase">Laptop</div>
                  </div>
                </div>
                
                <div className="mt-12 flex items-center justify-between">
                  <div className="font-mono text-[8px] text-app-textMuted tracking-widest font-bold">GENERATED BY AGENT_04</div>
                  <div className="w-2 h-2 rounded-full bg-[#F2EFE9] animate-ping opacity-50" />
                </div>
              </div>
            </div>
          </motion.div>

          {/* Right: The Headline (Slides from Right) */}
          <motion.div 
            style={{ x: rightX, opacity }}
            className="flex flex-col justify-center order-1 lg:order-2"
          >
            <h2 className="font-editorial text-5xl md:text-7xl lg:text-8xl font-extrabold uppercase text-app-textPrimary leading-[0.9] tracking-tighter mb-12">
              THEN AI<br />
              <span className="text-app-textMuted">ACTS.</span>
            </h2>
            
            <p className="mt-8 max-w-md font-sans text-app-textPrimary leading-relaxed text-xl font-light">
              The AI finds what you want and prepares the purchase. It creates a transaction proposal.
            </p>
            
            <p className="mt-6 max-w-md font-sans text-app-textMuted leading-relaxed text-lg">
              But before the money moves, the transaction must pass through the PayGuard Core. The system observes the intent.
            </p>
          </motion.div>

        </div>
      </section>
    </div>
  );
};
